// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (user_id, target_size, raw_url, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, user_id, status, raw_url, original_width, original_height, target_size, variant_sd, variant_hd, variant_raw, retry_count, error_message, created_at, updated_at
`

type CreateMediaAssetParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	TargetSize string      `json:"target_size"`
	RawUrl     pgtype.Text `json:"raw_url"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset, arg.UserID, arg.TargetSize, arg.RawUrl)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RawUrl,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.TargetSize,
		&i.VariantSd,
		&i.VariantHd,
		&i.VariantRaw,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, user_id, status, raw_url, original_width, original_height, target_size, variant_sd, variant_hd, variant_raw, retry_count, error_message, created_at, updated_at FROM media_assets WHERE id = $1
`

func (q *Queries) GetMediaAsset(ctx context.Context, id uuid.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RawUrl,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.TargetSize,
		&i.VariantSd,
		&i.VariantHd,
		&i.VariantRaw,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMediaFailed = `-- name: UpdateMediaFailed :exec
UPDATE media_assets
SET
    status = 'failed',
    error_message = $2,
    retry_count = retry_count + 1,
    updated_at = NOW()
WHERE id = $1
`

type UpdateMediaFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateMediaFailed(ctx context.Context, arg UpdateMediaFailedParams) error {
	_, err := q.db.Exec(ctx, updateMediaFailed, arg.ID, arg.ErrorMessage)
	return err
}

const updateMediaStatus = `-- name: UpdateMediaStatus :exec
UPDATE media_assets SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateMediaStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) error {
	_, err := q.db.Exec(ctx, updateMediaStatus, arg.ID, arg.Status)
	return err
}

const updateMediaVariants = `-- name: UpdateMediaVariants :one
UPDATE media_assets
SET
    variant_sd = COALESCE($2, variant_sd),
    variant_hd = COALESCE($3, variant_hd),
    variant_raw = COALESCE($4, variant_raw),
    status = 'completed',
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, status, raw_url, original_width, original_height, target_size, variant_sd, variant_hd, variant_raw, retry_count, error_message, created_at, updated_at
`

type UpdateMediaVariantsParams struct {
	ID         uuid.UUID   `json:"id"`
	VariantSd  pgtype.Text `json:"variant_sd"`
	VariantHd  pgtype.Text `json:"variant_hd"`
	VariantRaw pgtype.Text `json:"variant_raw"`
}

func (q *Queries) UpdateMediaVariants(ctx context.Context, arg UpdateMediaVariantsParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, updateMediaVariants,
		arg.ID,
		arg.VariantSd,
		arg.VariantHd,
		arg.VariantRaw,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.RawUrl,
		&i.OriginalWidth,
		&i.OriginalHeight,
		&i.TargetSize,
		&i.VariantSd,
		&i.VariantHd,
		&i.VariantRaw,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
