// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MediaAsset struct {
	ID             pgtype.UUID      `json:"id"`
	UserID         pgtype.UUID      `json:"user_id"`
	Status         string           `json:"status"`
	RawUrl         pgtype.Text      `json:"raw_url"`
	OriginalWidth  pgtype.Int4      `json:"original_width"`
	OriginalHeight pgtype.Int4      `json:"original_height"`
	TargetSize     string           `json:"target_size"`
	VariantSd      pgtype.Text      `json:"variant_sd"`
	VariantHd      pgtype.Text      `json:"variant_hd"`
	VariantRaw     pgtype.Text      `json:"variant_raw"`
	RetryCount     int32            `json:"retry_count"`
	ErrorMessage   pgtype.Text      `json:"error_message"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type RefreshToken struct {
	ID        int32            `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Token     string           `json:"token"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	Role      string           `json:"role"`
	AvatarSd  pgtype.Text      `json:"avatar_sd"`
	AvatarHd  pgtype.Text      `json:"avatar_hd"`
	AvatarRaw pgtype.Text      `json:"avatar_raw"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
