// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserWithPassword = `-- name: CreateUserWithPassword :one
INSERT INTO users (name, email, password)
VALUES ($1, $2, $3)
RETURNING id, name, email, role, avatar_sd, avatar_hd, avatar_raw, created_at
`

type CreateUserWithPasswordParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserWithPasswordRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	AvatarSd  pgtype.Text      `json:"avatar_sd"`
	AvatarHd  pgtype.Text      `json:"avatar_hd"`
	AvatarRaw pgtype.Text      `json:"avatar_raw"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateUserWithPassword(ctx context.Context, arg CreateUserWithPasswordParams) (CreateUserWithPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWithPassword, arg.Name, arg.Email, arg.Password)
	var i CreateUserWithPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.AvatarSd,
		&i.AvatarHd,
		&i.AvatarRaw,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, role FROM users WHERE email = $1
`

type GetUserByEmailRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password string      `json:"password"`
	Role     string      `json:"role"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, role, avatar_sd, avatar_hd, avatar_raw, created_at 
FROM users 
WHERE id = $1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	AvatarSd  pgtype.Text      `json:"avatar_sd"`
	AvatarHd  pgtype.Text      `json:"avatar_hd"`
	AvatarRaw pgtype.Text      `json:"avatar_raw"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.AvatarSd,
		&i.AvatarHd,
		&i.AvatarRaw,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
  name = COALESCE($2, name),
  email = COALESCE($3, email)
WHERE id = $1
RETURNING id, name, email, role, avatar_sd, avatar_hd, avatar_raw, created_at
`

type UpdateUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Name  pgtype.Text `json:"name"`
	Email pgtype.Text `json:"email"`
}

type UpdateUserRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	AvatarSd  pgtype.Text      `json:"avatar_sd"`
	AvatarHd  pgtype.Text      `json:"avatar_hd"`
	AvatarRaw pgtype.Text      `json:"avatar_raw"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.Email)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.AvatarSd,
		&i.AvatarHd,
		&i.AvatarRaw,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
SET 
  avatar_sd = COALESCE($2, avatar_sd),
  avatar_hd = COALESCE($3, avatar_hd),
  avatar_raw = COALESCE($4, avatar_raw)
WHERE id = $1
RETURNING id, name, email, role, avatar_sd, avatar_hd, avatar_raw, created_at
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID `json:"id"`
	AvatarSd  pgtype.Text `json:"avatar_sd"`
	AvatarHd  pgtype.Text `json:"avatar_hd"`
	AvatarRaw pgtype.Text `json:"avatar_raw"`
}

type UpdateUserAvatarRow struct {
	ID        pgtype.UUID      `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Role      string           `json:"role"`
	AvatarSd  pgtype.Text      `json:"avatar_sd"`
	AvatarHd  pgtype.Text      `json:"avatar_hd"`
	AvatarRaw pgtype.Text      `json:"avatar_raw"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UpdateUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar,
		arg.ID,
		arg.AvatarSd,
		arg.AvatarHd,
		arg.AvatarRaw,
	)
	var i UpdateUserAvatarRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.AvatarSd,
		&i.AvatarHd,
		&i.AvatarRaw,
		&i.CreatedAt,
	)
	return i, err
}
